function points2obj(vertices,normals,complete_filepath)
fid = fopen(complete_filepath,'w');
if fid == -1
    msg = strcat('Could not open the file in the path: ',filename);
    error(msg);
end

fprintf(fid,'#generated by Paulo Abelha (pauloabelha@gmail.com)');
fprintf(fid,'\n');
fprintf(fid,'#vertices and normals (same size each set)');
fprintf(fid,'\n');
fprintf(fid,'number_vertices');
fprintf(fid,'\n');
fprintf(fid,'%d',size(vertices,1));
fprintf(fid,'\n');
dlmwrite(complete_filepath,vertices,'delimiter',' ','-append');
dlmwrite(complete_filepath,normals,'delimiter',' ','-append');
end